# Generated by Django 6.0.4 on 2026-04-25 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_date_naissance_patient_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
