# Generated by Django 6.0.4 on 2026-04-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('medecin', 'Medecin'), ('patient', 'Patient'), ('secretaire', 'Secretaire'), ('infirmier', 'Infirmier'), ('comptable', 'Comptable'), ('securite', 'Securite'), ('chauffeur', 'Chauffeur')], default='patient', max_length=20),
        ),
    ]
