# Generated by Django 6.0.4 on 2026-04-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('validé', 'Validé'), ('annulé', 'Annulé')], default='en attente', max_length=20),
        ),
    ]
