# Generated by Django 6.0.4 on 2026-04-25 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
