# Generated by Django 6.0.4 on 2026-04-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin')),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendezvous.rendezvous')),
            ],
        ),
    ]
