# Generated by Django 6.0.4 on 2026-04-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0002_patient_date_naissance_patient_groupe_sanguin_and_more'),
        ('rendezvous', '0002_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='rendezvous',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rendezvous.rendezvous'),
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
        migrations.DeleteModel(
            name='Ordonnance',
        ),
    ]
