# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0003_ordonnance_medicament"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
