# Generated by Django 6.0.4 on 2026-04-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_ordonnance_medicament'),
        ('facturation', '0001_initial'),
        ('hospitalisation', '0004_chambre_alter_hospitalisation_motif_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiement',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='methode',
        ),
        migrations.AddField(
            model_name='facture',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.hospitalisation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('non payé', 'Non payé'), ('payé', 'Payé')], default='non payé', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('carte', 'Carte'), ('virement', 'Virement')], default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture'),
        ),
    ]
