# Generated by Codex on 2026-05-01

from django.db import migrations, models


def normalize_facture_status(apps, schema_editor):
    Facture = apps.get_model("facturation", "Facture")
    Facture.objects.filter(statut__in=["non payé", "non payÃ©", "non payÃƒÂ©", "impayé"]).update(statut="impaye")
    Facture.objects.filter(statut__in=["payé", "payÃ©", "payÃƒÂ©"]).update(statut="paye")


class Migration(migrations.Migration):

    dependencies = [
        ("facturation", "0002_rename_date_paiement_paiement_date_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_facture_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="facture",
            name="statut",
            field=models.CharField(
                choices=[("impaye", "Impaye"), ("paye", "Paye")],
                default="impaye",
                max_length=20,
            ),
        ),
    ]
