# Generated by Django 6.0.4 on 2026-04-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
        ('personnel', '0002_personnel_actif_alter_personnel_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionambulance',
            name='chauffeur',
            field=models.ForeignKey(limit_choices_to={'fonction': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel'),
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='missionambulance',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='missionambulance',
            name='patient',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='chauffeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'fonction': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='matricule',
            field=models.CharField(default='AMB-001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='type',
            field=models.CharField(default='domicile', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionambulance',
            name='lieu_arrivee',
            field=models.CharField(default='clinique', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionambulance',
            name='lieu_depart',
            field=models.CharField(default='inconnu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionambulance',
            name='patient_nom',
            field=models.CharField(default='standard', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionambulance',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminée', 'Terminée')], default='en cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='missionambulance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Chauffeur',
        ),
    ]
