# Generated by Django 6.0.4 on 2026-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_alter_missionambulance_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='matricule',
            field=models.CharField(default='AMB-XXX', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='missionambulance',
            name='lieu_arrivee',
            field=models.CharField(default='clinique', max_length=255),
        ),
        migrations.AlterField(
            model_name='missionambulance',
            name='lieu_depart',
            field=models.CharField(default='domicile', max_length=255),
        ),
        migrations.AlterField(
            model_name='missionambulance',
            name='patient_nom',
            field=models.CharField(default='inconnu', max_length=100),
        ),
    ]
