# Generated by Django 6.0.4 on 2026-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_embauche',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
