# Generated by Django 6.0.4 on 2026-04-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_actif_alter_personnel_adresse_and_more'),
        ('visiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvisite',
            name='agent_securite',
            field=models.ForeignKey(limit_choices_to={'fonction': 'securite'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='journalvisite',
            name='motif',
            field=models.CharField(default='visite', max_length=255),
        ),
        migrations.AddField(
            model_name='journalvisite',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('terminé', 'Terminé')], default='en cours', max_length=20),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='cin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
