# Generated by Codex on 2026-05-01

from django.db import migrations, models


def normalize_journal_status(apps, schema_editor):
    JournalVisite = apps.get_model("visiteurs", "JournalVisite")
    JournalVisite.objects.filter(statut__in=["en cours", "en_cours"]).update(statut="en_cours")
    JournalVisite.objects.filter(statut__in=["terminé", "terminÃ©", "sorti"]).update(statut="sorti")


class Migration(migrations.Migration):

    dependencies = [
        ("visiteurs", "0002_journalvisite_agent_securite_journalvisite_motif_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_journal_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="journalvisite",
            name="statut",
            field=models.CharField(
                choices=[("en_cours", "En cours"), ("sorti", "Sorti")],
                default="en_cours",
                max_length=20,
            ),
        ),
    ]
