# Generated by Codex on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


def copy_journal_to_visite(apps, schema_editor):
    JournalVisite = apps.get_model("visiteurs", "JournalVisite")
    Visite = apps.get_model("visiteurs", "Visite")

    for journal in JournalVisite.objects.all():
        statut = journal.statut
        if statut in ["en cours", "en_cours"]:
            statut = "en_cours"
        elif statut in ["terminé", "terminÃ©", "sorti"]:
            statut = "sorti"

        visite = Visite.objects.create(
            visiteur_id=journal.visiteur_id,
            motif=journal.motif or "visite",
            date_sortie=journal.date_sortie,
            statut=statut,
        )
        Visite.objects.filter(id=visite.id).update(date_entree=journal.date_entree)


class Migration(migrations.Migration):

    dependencies = [
        ("visiteurs", "0003_normalize_journalvisite_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("motif", models.CharField(max_length=255)),
                ("date_entree", models.DateTimeField(auto_now_add=True)),
                ("date_sortie", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En cours"), ("sorti", "Sorti")],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                (
                    "visiteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visites",
                        to="visiteurs.visiteur",
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_journal_to_visite, migrations.RunPython.noop),
    ]
