# Generated by Django 6.0.4 on 2026-04-25 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_ordonnance_consultation_and_more'),
        ('hospitalisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='chambre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='motif',
            field=models.TextField(default='motif temporaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('sorti', 'Sorti')], default='en cours', max_length=20),
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
