# Generated by Django 6.0.4 on 2026-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0002_alter_hospitalisation_chambre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisation',
            name='motif',
            field=models.TextField(blank=True),
        ),
    ]
