# Generated by Django 6.0.4 on 2026-04-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalisation', '0003_alter_hospitalisation_motif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='motif',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.chambre'),
        ),
    ]
