# Generated by Codex on 2026-05-01

from django.db import migrations, models


def normalize_hospitalisation_status(apps, schema_editor):
    Hospitalisation = apps.get_model("hospitalisation", "Hospitalisation")
    Hospitalisation.objects.filter(statut__in=["en cours", "en_cours"]).update(statut="en_cours")
    Hospitalisation.objects.filter(statut__in=["sorti", "termine", "terminé", "terminÃ©"]).update(statut="termine")


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalisation", "0004_chambre_alter_hospitalisation_motif_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_hospitalisation_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="hospitalisation",
            name="statut",
            field=models.CharField(
                choices=[("en_cours", "En cours"), ("termine", "Termine")],
                default="en_cours",
                max_length=20,
            ),
        ),
    ]
