# Generated by Django 6.0.4 on 2026-04-25 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='experience',
        ),
        migrations.AddField(
            model_name='medecin',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='numero_ordre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
