# Generated by Django 6.0.4 on 2026-04-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        ('specialites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialites.specialite'),
        ),
    ]
