# Generated by Django 6.0.4 on 2026-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_remove_medecin_experience_medecin_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='experience',
            field=models.IntegerField(blank=True, help_text="Années d'expérience", null=True),
        ),
    ]
