# Generated by Django 6.0.4 on 2026-04-30 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0003_medecin_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
